version: '3.5'
services:

  kafka-manager:
    build:
      context: '../'
      dockerfile: './ui/Dockerfile'
    image: 'epam/eco-kafka-manager:latest'
    hostname: 'kafka-manager'
    environment:
      - 'KAFKA_SERVERS_URL=${KAFKA_SERVERS_URL:-}'
      - 'JAVA_OPTS=${JAVA_OPTS:-}'
    ports:
      - '8082:8082'
    restart: 'on-failure'
